use serde::Serialize;
use std::path::{Path, PathBuf};

/// An installed audio plugin found on the user's system.
#[derive(Serialize, Clone, Debug)]
#[serde(rename_all = "camelCase")]
pub struct InstalledPlugin {
    pub name: String,
    pub vendor: String,
    pub format: String,    // "AU", "VST3", "VST", "CLAP"
    pub path: String,
    pub version: Option<String>,
}

/// Scan the system for installed audio plugins (AU, VST3, VST, CLAP).
pub fn scan_all() -> Vec<InstalledPlugin> {
    let mut plugins = Vec::new();

    #[cfg(target_os = "macos")]
    {
        // Audio Units
        scan_directory(
            &dirs::home_dir().unwrap_or_default().join("Library/Audio/Plug-Ins/Components"),
            "AU", &mut plugins,
        );
        scan_directory(
            Path::new("/Library/Audio/Plug-Ins/Components"),
            "AU", &mut plugins,
        );

        // VST3
        scan_directory(
            &dirs::home_dir().unwrap_or_default().join("Library/Audio/Plug-Ins/VST3"),
            "VST3", &mut plugins,
        );
        scan_directory(
            Path::new("/Library/Audio/Plug-Ins/VST3"),
            "VST3", &mut plugins,
        );

        // VST (legacy)
        scan_directory(
            &dirs::home_dir().unwrap_or_default().join("Library/Audio/Plug-Ins/VST"),
            "VST", &mut plugins,
        );
        scan_directory(
            Path::new("/Library/Audio/Plug-Ins/VST"),
            "VST", &mut plugins,
        );

        // CLAP
        scan_directory(
            &dirs::home_dir().unwrap_or_default().join("Library/Audio/Plug-Ins/CLAP"),
            "CLAP", &mut plugins,
        );
        scan_directory(
            Path::new("/Library/Audio/Plug-Ins/CLAP"),
            "CLAP", &mut plugins,
        );
    }

    #[cfg(target_os = "windows")]
    {
        // VST3
        scan_directory(
            Path::new(r"C:\Program Files\Common Files\VST3"),
            "VST3", &mut plugins,
        );

        // VST (legacy)
        scan_directory(
            Path::new(r"C:\Program Files\VSTPlugins"),
            "VST", &mut plugins,
        );
        scan_directory(
            Path::new(r"C:\Program Files\Steinberg\VSTPlugins"),
            "VST", &mut plugins,
        );

        // CLAP
        scan_directory(
            Path::new(r"C:\Program Files\Common Files\CLAP"),
            "CLAP", &mut plugins,
        );
    }

    // Deduplicate by name (same plugin may exist in multiple formats)
    plugins.sort_by(|a, b| a.name.cmp(&b.name));
    plugins.dedup_by(|a, b| a.name == b.name && a.format == b.format);

    plugins
}

/// Scan a directory for plugin bundles/files.
fn scan_directory(dir: &Path, format: &str, plugins: &mut Vec<InstalledPlugin>) {
    let entries = match std::fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return, // Directory doesn't exist or not accessible
    };

    for entry in entries.flatten() {
        let path = entry.path();
        let name = entry.file_name().to_string_lossy().to_string();

        // Skip hidden files
        if name.starts_with('.') {
            continue;
        }

        let (plugin_name, vendor) = match format {
            "AU" => {
                // AU plugins are .component bundles
                if name.ends_with(".component") {
                    let clean = name.trim_end_matches(".component").to_string();
                    let vendor = extract_vendor_from_au(&path);
                    (clean, vendor)
                } else {
                    continue;
                }
            }
            "VST3" => {
                if name.ends_with(".vst3") {
                    let clean = name.trim_end_matches(".vst3").to_string();
                    let vendor = extract_vendor_from_path(&path);
                    (clean, vendor)
                } else if path.is_dir() {
                    // VST3 folder (contains .vst3 files inside)
                    scan_directory(&path, format, plugins);
                    continue;
                } else {
                    continue;
                }
            }
            "VST" => {
                if name.ends_with(".vst") {
                    let clean = name.trim_end_matches(".vst").to_string();
                    (clean, String::new())
                } else {
                    continue;
                }
            }
            "CLAP" => {
                if name.ends_with(".clap") {
                    let clean = name.trim_end_matches(".clap").to_string();
                    (clean, String::new())
                } else {
                    continue;
                }
            }
            _ => continue,
        };

        plugins.push(InstalledPlugin {
            name: plugin_name,
            vendor,
            format: format.to_string(),
            path: path.to_string_lossy().to_string(),
            version: None,
        });
    }
}

/// Try to extract vendor name from an AU component's Info.plist.
fn extract_vendor_from_au(path: &Path) -> String {
    let plist_path = path.join("Contents/Info.plist");
    if let Ok(content) = std::fs::read_to_string(&plist_path) {
        // Simple XML parsing — look for CFBundleIdentifier
        if let Some(start) = content.find("<key>CFBundleIdentifier</key>") {
            let rest = &content[start..];
            if let Some(s) = rest.find("<string>") {
                if let Some(e) = rest[s + 8..].find("</string>") {
                    let bundle_id = &rest[s + 8..s + 8 + e];
                    // Bundle IDs like "com.xferrecords.Serum" → "xferrecords"
                    let parts: Vec<&str> = bundle_id.split('.').collect();
                    if parts.len() >= 2 {
                        return parts[1].to_string();
                    }
                }
            }
        }
    }
    String::new()
}

/// Extract vendor from path (some VST3 plugins are in vendor subfolders).
fn extract_vendor_from_path(path: &Path) -> String {
    // If the parent folder isn't the root VST3 folder, it's likely the vendor name
    if let Some(parent) = path.parent() {
        let parent_name = parent.file_name().unwrap_or_default().to_string_lossy().to_string();
        if parent_name != "VST3" && parent_name != "Components" {
            return parent_name;
        }
    }
    String::new()
}

/// Known plugin names used in WMDM templates — for matching against
/// installed plugins. Generated from:
///   wmdm-daw-parser/extractors/plugin_registry.py
/// Regenerate with:
///   cd wmdm-daw-parser && python3 tools/export_rust_registry.py
pub const KNOWN_PLUGINS: &[(&str, &[&str])] = &[
    ("Serum", &["Serum", "xfer serum", "com.xferrecords.serum"]),
    ("Serum 2", &["Serum 2", "serum2", "serum 2", "com.xferrecords.serum2"]),
    ("Serum FX", &["Serum FX", "serumfx", "serum fx"]),
    ("Nerve", &["Nerve", "xfer nerve"]),
    ("Cthulhu", &["Cthulhu", "xfer cthulhu"]),
    ("Sylenth1", &["Sylenth1", "sylenth", "lennardigital sylenth1"]),
    ("Spire", &["Spire", "reveal sound spire", "revealsound spire"]),
    ("Omnisphere", &["Omnisphere", "omnisphere 2", "spectrasonics omnisphere"]),
    ("Keyscape", &["Keyscape", "spectrasonics keyscape"]),
    ("Trilian", &["Trilian", "spectrasonics trilian"]),
    ("Stylus RMX", &["Stylus RMX", "stylus rmx", "spectrasonics stylus"]),
    ("Kontakt", &["Kontakt", "kontakt 5", "kontakt 6", "kontakt 7", "kontakt 8", "kontakt player", "ni kontakt", "native instruments kontakt"]),
    ("Massive", &["Massive", "ni massive", "native instruments massive"]),
    ("Massive X", &["Massive X", "massivex", "massive x"]),
    ("Reaktor", &["Reaktor", "reaktor 6", "ni reaktor", "native instruments reaktor"]),
    ("Reaktor Blocks", &["Reaktor Blocks", "reaktor blocks"]),
    ("FM8", &["FM8", "ni fm8"]),
    ("Absynth 5", &["Absynth 5", "absynth", "ni absynth"]),
    ("Battery 4", &["Battery 4", "battery", "ni battery"]),
    ("Maschine", &["Maschine", "maschine 2", "ni maschine"]),
    ("Monark", &["Monark"]),
    ("Razor", &["Razor"]),
    ("Rounds", &["Rounds"]),
    ("Form", &["Form"]),
    ("Kinetic Treats", &["Kinetic Treats"]),
    ("Retro Machines Mk2", &["Retro Machines Mk2"]),
    ("Dimension Expander", &["Dimension Expander", "dimensionexpander", "dimension expander_x64", "dimension expander 64"]),
    ("Transient Master", &["Transient Master", "transientmaster", "transient master_x64", "transient master 64"]),
    ("Supercharger", &["Supercharger", "supercharger gt"]),
    ("Solid Dynamics", &["Solid Dynamics", "solid bus comp", "solid dynamics_x64"]),
    ("Solid EQ", &["Solid EQ", "solideq"]),
    ("VC 160", &["VC 160", "vc-160"]),
    ("VC 2A", &["VC 2A", "vc-2a"]),
    ("VC 76", &["VC 76", "vc-76"]),
    ("Replika XT", &["Replika XT", "replika"]),
    ("Raum", &["Raum"]),
    ("Choral", &["Choral"]),
    ("Phasis", &["Phasis"]),
    ("Flair", &["Flair"]),
    ("Mod Pack", &["Mod Pack"]),
    ("Crush Pack", &["Crush Pack"]),
    ("Driver", &["Driver"]),
    ("Molekular", &["Molekular"]),
    ("Pigments", &["Pigments", "pigments 2", "pigments 3", "pigments 4", "pigments 5", "arturia pigments"]),
    ("Analog Lab", &["Analog Lab", "analog lab v", "analog lab pro", "analog lab intro", "arturia analog lab"]),
    ("Mini V", &["Mini V", "minimoog v", "mini v3", "arturia mini v"]),
    ("CS-80 V", &["CS-80 V", "cs80 v", "cs-80"]),
    ("Jup-8 V", &["Jup-8 V", "jupiter-8 v", "jup8 v"]),
    ("Prophet V", &["Prophet V", "prophet vs", "prophet-5 v", "prophet-v"]),
    ("Matrix-12 V", &["Matrix-12 V", "matrix 12 v"]),
    ("Modular V", &["Modular V", "modular v"]),
    ("ARP 2600 V", &["ARP 2600 V", "arp2600 v"]),
    ("Oberheim SEM V", &["Oberheim SEM V", "sem v"]),
    ("Piano V", &["Piano V", "piano v3"]),
    ("Stage-73 V", &["Stage-73 V", "stage 73"]),
    ("Wurli V", &["Wurli V"]),
    ("B-3 V", &["B-3 V", "b3 v"]),
    ("Vox Continental V", &["Vox Continental V"]),
    ("Farfisa V", &["Farfisa V"]),
    ("Mellotron V", &["Mellotron V"]),
    ("Solina V", &["Solina V"]),
    ("DX7 V", &["DX7 V", "dx7-v"]),
    ("Synclavier V", &["Synclavier V"]),
    ("Synthi V", &["Synthi V"]),
    ("Emulator II V", &["Emulator II V", "emulator 2 v"]),
    ("Buchla Easel V", &["Buchla Easel V"]),
    ("CZ V", &["CZ V", "cz-v"]),
    ("OP-Xa V", &["OP-Xa V", "op-x"]),
    ("MS-20 V", &["MS-20 V", "ms20 v"]),
    ("Augmented Strings", &["Augmented Strings"]),
    ("Augmented Voices", &["Augmented Voices"]),
    ("Augmented Brass", &["Augmented Brass"]),
    ("Augmented Woodwinds", &["Augmented Woodwinds"]),
    ("Augmented Grand Piano", &["Augmented Grand Piano"]),
    ("Matrix Brute V", &["Matrix Brute V", "matrix-brute", "matrixbrute v"]),
    ("Spark 2", &["Spark 2", "arturia spark", "spark2"]),
    ("Clavinet V", &["Clavinet V", "clav v"]),
    ("Acid V", &["Acid V", "arturia acid"]),
    ("Augmented Piano", &["Augmented Piano"]),
    ("Comp VCA-65", &["Comp VCA-65", "vca-65", "vca65", "comp vca65"]),
    ("Comp FET-76", &["Comp FET-76", "fet-76", "fet76", "comp fet76"]),
    ("Comp TUBE-STA", &["Comp TUBE-STA", "tube-sta", "tubesta"]),
    ("Comp DIODE-609", &["Comp DIODE-609", "diode-609", "diode 609"]),
    ("Bus FORCE", &["Bus FORCE", "bus-force", "busforce"]),
    ("EQ SITRAL-295", &["EQ SITRAL-295", "sitral-295", "sitral 295"]),
    ("EQ MS-20", &["EQ MS-20", "arturia ms-20 eq"]),
    ("Delay MEMORY-BRIGADE", &["Delay MEMORY-BRIGADE", "memory-brigade", "memory brigade"]),
    ("Delay TAPE-201", &["Delay TAPE-201", "tape-201", "tape 201"]),
    ("Delay BRIGADE", &["Delay BRIGADE", "delay brigade"]),
    ("Delay ETERNITY", &["Delay ETERNITY", "eternity"]),
    ("Rev PLATE-140", &["Rev PLATE-140", "plate-140", "plate 140"]),
    ("Rev SPRING-636", &["Rev SPRING-636", "spring-636", "spring 636"]),
    ("Rev INTENSITY", &["Rev INTENSITY", "rev intensity"]),
    ("Rev LX-24", &["Rev LX-24", "lx-24", "lx 24"]),
    ("Filter M12", &["Filter M12", "m12 filter", "arturia filter m12"]),
    ("Filter MINI", &["Filter MINI", "filter mini"]),
    ("Filter SEM", &["Filter SEM", "filter-sem"]),
    ("Pre 1973", &["Pre 1973", "pre-1973", "preamp 1973"]),
    ("Pre TridA", &["Pre TridA", "pre trid a", "tridA"]),
    ("Pre V76", &["Pre V76", "v76"]),
    ("Dist COLDFIRE", &["Dist COLDFIRE", "coldfire"]),
    ("Dist TUBE-CULTURE", &["Dist TUBE-CULTURE", "tube culture", "tube-culture"]),
    ("Dist OPAMP-21", &["Dist OPAMP-21", "opamp-21", "opamp 21"]),
    ("Chorus DIMENSION-D", &["Chorus DIMENSION-D", "dimension-d", "chorus dimension d"]),
    ("Chorus JUN-6", &["Chorus JUN-6", "jun-6 chorus", "jun 6"]),
    ("Phaser BI-TRON", &["Phaser BI-TRON", "bi-tron", "bitron"]),
    ("Flanger BL-20", &["Flanger BL-20", "bl-20"]),
    ("Tape MELLO-FI", &["Tape MELLO-FI", "mello-fi", "mellofi"]),
    ("Efx FRAGMENTS", &["Efx FRAGMENTS", "fragments"]),
    ("Efx MOTIONS", &["Efx MOTIONS", "arturia motions"]),
    ("Efx REFRACT", &["Efx REFRACT", "refract"]),
    ("Diva", &["Diva", "u-he diva", "uhe diva"]),
    ("Hive", &["Hive", "u-he hive", "hive 2"]),
    ("Zebra2", &["Zebra2", "u-he zebra", "zebra 2"]),
    ("Zebra3", &["Zebra3", "zebra 3", "zebralette 3"]),
    ("ZebraHZ", &["ZebraHZ", "zebra hz"]),
    ("Bazille", &["Bazille", "u-he bazille"]),
    ("ACE", &["ACE", "u-he ace"]),
    ("Repro-1", &["Repro-1", "u-he repro", "repro 1"]),
    ("Repro-5", &["Repro-5", "repro 5"]),
    ("Satin", &["Satin", "u-he satin"]),
    ("Presswerk", &["Presswerk", "u-he presswerk"]),
    ("Colour Copy", &["Colour Copy", "colourcopy", "u-he colour copy"]),
    ("Twangström", &["Twangström", "twangstrom"]),
    ("Filterscape", &["Filterscape", "u-he filterscape"]),
    ("Uhbik", &["Uhbik", "u-he uhbik"]),
    ("TyrellN6", &["TyrellN6", "tyrell n6"]),
    ("Podolski", &["Podolski"]),
    ("Triple Cheese", &["Triple Cheese", "triplecheese"]),
    ("Phase Plant", &["Phase Plant", "phaseplant", "kilohearts phase plant"]),
    ("Snap Heap", &["Snap Heap", "snapheap"]),
    ("Multipass", &["Multipass", "kilohearts multipass"]),
    ("Carve EQ", &["Carve EQ", "carveeq"]),
    ("Faturator", &["Faturator"]),
    ("Disperser", &["Disperser"]),
    ("Transient Shaper", &["Transient Shaper", "transient shaper 64", "transient shaper_x64", "kilohearts transient shaper"]),
    ("Vital", &["Vital", "vitalium"]),
    ("Nexus", &["Nexus", "nexus 3", "nexus3", "nexus 4", "nexus4", "refx nexus"]),
    ("Avenger", &["Avenger", "vps avenger", "vengeance avenger"]),
    ("Metrum", &["Metrum"]),
    ("Predator 2", &["Predator 2", "predator2"]),
    ("Predator 3", &["Predator 3", "predator3"]),
    ("Blue II", &["Blue II", "blue 2", "blueii"]),
    ("Blue 3", &["Blue 3", "blue3", "blue iii"]),
    ("Go2", &["Go2", "rob papen go2"]),
    ("Punch", &["Punch", "punch 2", "punch-bd", "punch electro"]),
    ("SubBoomBass 2", &["SubBoomBass 2", "subboombass"]),
    ("Quad", &["Quad", "rob papen quad"]),
    ("RP-Delay", &["RP-Delay", "rp delay"]),
    ("RP-Distort", &["RP-Distort", "rp distort"]),
    ("RP-Verb", &["RP-Verb", "rp verb"]),
    ("SynthMaster 2", &["SynthMaster 2", "synthmaster2", "synthmaster 2.9"]),
    ("SynthMaster One", &["SynthMaster One", "synthmasterone"]),
    ("SynthMaster Player", &["SynthMaster Player"]),
    ("DUNE 3", &["DUNE 3", "dune3", "dune iii"]),
    ("DUNE 4", &["DUNE 4", "dune4", "dune iv"]),
    ("The Legend HZ", &["The Legend HZ", "the legend"]),
    ("Obsession", &["Obsession"]),
    ("Surge XT", &["Surge XT", "surge xt", "surgext"]),
    ("Surge XT Effects", &["Surge XT Effects", "surge xt fx"]),
    ("Gladiator", &["Gladiator", "gladiator 3"]),
    ("Saurus", &["Saurus", "saurus 3"]),
    ("ElectraX", &["ElectraX", "electrax2"]),
    ("NanoHost", &["NanoHost"]),
    ("UltraSpace", &["UltraSpace"]),
    ("Minimonsta", &["Minimonsta", "minimonsta2"]),
    ("M-Tron Pro", &["M-Tron Pro", "mtron pro"]),
    ("impOSCar 2", &["impOSCar 2"]),
    ("OB-E", &["OB-E"]),
    ("OB-X", &["OB-X", "ob-x8"]),
    ("VSM III", &["VSM III"]),
    ("TAL-U-No-LX", &["TAL-U-No-LX", "tal-u-no", "tal uno"]),
    ("TAL-J-8", &["TAL-J-8", "tal j8"]),
    ("TAL-BassLine", &["TAL-BassLine", "tal bassline"]),
    ("TAL-Sampler", &["TAL-Sampler"]),
    ("Exhale", &["Exhale", "output exhale"]),
    ("Analog Brass & Winds", &["Analog Brass & Winds", "analog brass"]),
    ("Analog Strings", &["Analog Strings"]),
    ("Signal", &["Signal", "output signal"]),
    ("Arcade", &["Arcade", "output arcade"]),
    ("Substance", &["Substance", "output substance"]),
    ("REV", &["REV", "output rev"]),
    ("Portal", &["Portal", "output portal"]),
    ("Thermal", &["Thermal", "output thermal"]),
    ("Movement", &["Movement", "output movement"]),
    ("Heat Up 3", &["Heat Up 3", "heat up", "heatup"]),
    ("Sektor", &["Sektor", "sektor 1.4"]),
    ("808 Studio II", &["808 Studio II", "808 studio", "808studio"]),
    ("Dynamic Eq", &["Dynamic Eq"]),
    ("Reverse", &["Reverse", "initial audio reverse"]),
    ("ANA 2", &["ANA 2", "ana2"]),
    ("Kick 2", &["Kick 2", "kick2"]),
    ("Kick 3", &["Kick 3", "kick3"]),
    ("M1", &["M1", "korg m1", "korg-m1", "m1le"]),
    ("MS-20", &["MS-20", "korg ms-20", "ms20", "legacy ms-20", "ms-20fs"]),
    ("Polysix", &["Polysix", "korg polysix", "legacy polysix"]),
    ("Mono/Poly", &["Mono/Poly", "monopoly", "korg mono/poly", "mono poly"]),
    ("WAVESTATION", &["WAVESTATION", "wavestation", "korg wavestation"]),
    ("Triton", &["Triton", "korg triton", "triton extreme", "legacy triton"]),
    ("Prophecy", &["Prophecy", "korg prophecy"]),
    ("ARP Odyssey", &["ARP Odyssey", "arp-odyssey", "korg odyssey", "arp odissey"]),
    ("KORG Collection", &["KORG Collection", "korg collection 3", "korg collection 4"]),
    ("MDE-X", &["MDE-X", "korg mde-x", "mde x"]),
    ("Kaossilator", &["Kaossilator", "korg kaossilator"]),
    ("Gadget", &["Gadget", "korg gadget"]),
    ("Electribe R", &["Electribe R", "electribe-r"]),
    ("iWAVESTATION", &["iWAVESTATION", "iwavestation"]),
    ("iM1", &["iM1"]),
    ("iMono/Poly", &["iMono/Poly", "imonopoly"]),
    ("iPolysix", &["iPolysix"]),
    ("iElectric", &["iElectric"]),
    ("LegacyCell", &["LegacyCell", "legacy cell"]),
    ("Jupiter-8", &["Jupiter-8", "jupiter 8", "jupiter-8v", "roland jupiter-8"]),
    ("Jupiter-4", &["Jupiter-4", "jupiter 4"]),
    ("Juno-60", &["Juno-60", "juno 60", "roland juno-60"]),
    ("Juno-106", &["Juno-106", "juno 106", "roland juno-106"]),
    ("SH-101", &["SH-101", "sh101", "roland sh-101"]),
    ("SH-2", &["SH-2", "sh2", "roland sh-2"]),
    ("JX-3P", &["JX-3P", "jx3p", "roland jx-3p"]),
    ("JX-8P", &["JX-8P", "jx8p", "roland jx-8p"]),
    ("JD-800", &["JD-800", "jd800", "roland jd-800"]),
    ("D-50", &["D-50", "d50", "roland d-50"]),
    ("System-8", &["System-8", "system 8", "roland system-8"]),
    ("System-1", &["System-1", "system 1"]),
    ("System-100", &["System-100", "system 100"]),
    ("TR-808 Software", &["TR-808 Software", "tr-808", "tr808", "roland tr-808"]),
    ("TR-909 Software", &["TR-909 Software", "tr-909", "tr909", "roland tr-909"]),
    ("TR-707 Software", &["TR-707 Software", "tr-707", "tr707", "roland tr-707"]),
    ("TR-606 Software", &["TR-606 Software", "tr-606", "tr606"]),
    ("TR-727 Software", &["TR-727 Software", "tr-727", "tr727"]),
    ("TB-303 Software", &["TB-303 Software", "tb-303", "tb303", "roland tb-303"]),
    ("JV-1080", &["JV-1080", "jv1080"]),
    ("JV-2080", &["JV-2080", "jv2080"]),
    ("XV-5080", &["XV-5080", "xv5080"]),
    ("SRX Electric Piano", &["SRX Electric Piano", "srx electric", "srx-electric"]),
    ("SRV-2000", &["SRV-2000", "srv 2000", "srv2000"]),
    ("SDE-3000", &["SDE-3000", "sde 3000", "sde3000"]),
    ("SDD-320", &["SDD-320", "sdd 320", "sdd320"]),
    ("RE-201", &["RE-201", "re201", "space echo", "roland re-201"]),
    ("Zenology", &["Zenology", "zenology pro"]),
    ("Roland Cloud", &["Roland Cloud", "roland cloud manager"]),
    ("Thor", &["Thor", "reason thor", "propellerhead thor"]),
    ("Subtractor", &["Subtractor", "reason subtractor"]),
    ("Malström", &["Malström", "malstrom", "malstroem"]),
    ("NN-XT", &["NN-XT", "nnxt"]),
    ("NN-19", &["NN-19", "nn19"]),
    ("Kong", &["Kong", "reason kong"]),
    ("Dr. Octo Rex", &["Dr. Octo Rex", "dr octo rex", "rex2 loop player"]),
    ("Europa", &["Europa", "reason europa"]),
    ("Parsec", &["Parsec", "reason parsec"]),
    ("Grain", &["Grain", "reason grain"]),
    ("Algoritm", &["Algoritm"]),
    ("Radical Piano", &["Radical Piano"]),
    ("Complex 1", &["Complex 1", "complex-1"]),
    ("Polar", &["Polar", "reason polar"]),
    ("Pulverizer", &["Pulverizer", "the echo pulverizer"]),
    ("Monark", &["Monark", "ni monark"]),
    ("HALion", &["HALion", "halion sonic", "halion 7"]),
    ("Padshop", &["Padshop", "padshop 2", "padshop pro"]),
    ("Retrologue", &["Retrologue", "retrologue 2"]),
    ("Groove Agent", &["Groove Agent", "groove agent 5"]),
    ("Addictive Drums 2", &["Addictive Drums 2", "addictive drums", "xln addictive drums"]),
    ("Addictive Keys", &["Addictive Keys", "xln addictive keys"]),
    ("RC-20 Retro Color", &["RC-20 Retro Color", "rc-20", "rc 20 retro"]),
    ("DS-10 Drum Shaper", &["DS-10 Drum Shaper", "ds-10"]),
    ("EZdrummer 3", &["EZdrummer 3", "ezdrummer", "ez drummer"]),
    ("Superior Drummer 3", &["Superior Drummer 3", "superior drummer", "sd3"]),
    ("EZbass", &["EZbass", "ez bass"]),
    ("EZkeys", &["EZkeys", "ez keys"]),
    ("EZmix 3", &["EZmix 3", "ezmix"]),
    ("Virtual Drummer", &["Virtual Drummer", "ujam virtual drummer", "vd-phat", "vd-deep", "vd-solid", "vd-heavy"]),
    ("Virtual Bassist", &["Virtual Bassist", "ujam virtual bassist", "vb-mellow", "vb-rowdy", "vb-royal"]),
    ("Virtual Guitarist", &["Virtual Guitarist", "ujam virtual guitarist", "vg-iron", "vg-sparkle", "vg-silk", "vg-carbon"]),
    ("Beatmaker", &["Beatmaker", "ujam beatmaker", "bm-nemesis", "bm-void", "bm-dope"]),
    ("Finisher NEO", &["Finisher NEO", "finisher"]),
    ("SSD 5", &["SSD 5", "steven slate drums", "ssd5"]),
    ("GetGood Drums", &["GetGood Drums", "ggd modern", "ggd one kit"]),
    ("Spitfire Audio Player", &["Spitfire Audio Player", "spitfire audio", "spitfire player", "bbc symphony", "hans zimmer strings", "albion one"]),
    ("LABS", &["LABS", "spitfire labs"]),
    ("BBC Symphony Orchestra", &["BBC Symphony Orchestra", "bbcso", "bbc so core"]),
    ("Abbey Road One", &["Abbey Road One", "abbey road one orchestral"]),
    ("Play", &["Play", "eastwest play"]),
    ("Opus", &["Opus", "eastwest opus"]),
    ("Hollywood Strings", &["Hollywood Strings"]),
    ("Hollywood Brass", &["Hollywood Brass"]),
    ("Hollywood Orchestra", &["Hollywood Orchestra"]),
    ("ProDrummer", &["ProDrummer"]),
    ("SINE Player", &["SINE Player", "sine player", "orchestral tools sine"]),
    ("Berlin Strings", &["Berlin Strings"]),
    ("Berlin Brass", &["Berlin Brass"]),
    ("Metropolis Ark", &["Metropolis Ark"]),
    ("Gravity", &["Gravity", "heavyocity gravity"]),
    ("Novo", &["Novo", "heavyocity novo"]),
    ("Damage 2", &["Damage 2", "heavyocity damage", "damage2"]),
    ("Ghostwriter", &["Ghostwriter", "heavyocity ghostwriter"]),
    ("Vocalise 3", &["Vocalise 3", "heavyocity vocalise", "vocalise3"]),
    ("Aeon", &["Aeon", "aeon collection"]),
    ("Intimate Textures", &["Intimate Textures"]),
    ("Chromaphone 3", &["Chromaphone 3", "chromaphone"]),
    ("Strum GS-2", &["Strum GS-2", "strum gs"]),
    ("Ultra Analog VA-3", &["Ultra Analog VA-3", "ultra analog"]),
    ("Tassman 4", &["Tassman 4", "tassman"]),
    ("Lounge Lizard EP-4", &["Lounge Lizard EP-4", "lounge lizard"]),
    ("String Studio VS-3", &["String Studio VS-3", "string studio"]),
    ("Pianoteq", &["Pianoteq", "pianoteq 8", "pianoteq pro"]),
    ("Equator 2", &["Equator 2", "roli equator"]),
    ("Sforzando", &["Sforzando"]),
    ("Chipsounds", &["Chipsounds"]),
    ("SWAM", &["SWAM", "swam strings", "swam brass", "swam woodwinds"]),
    ("Archetype: Nolly", &["Archetype: Nolly", "archetype nolly"]),
    ("Archetype: Plini", &["Archetype: Plini", "archetype plini"]),
    ("Archetype: Gojira", &["Archetype: Gojira", "archetype gojira"]),
    ("Archetype: Petrucci", &["Archetype: Petrucci", "archetype petrucci"]),
    ("Archetype: Rabea", &["Archetype: Rabea"]),
    ("Archetype: Tim Henson", &["Archetype: Tim Henson"]),
    ("Parallax", &["Parallax", "neural parallax"]),
    ("Darkglass Ultra", &["Darkglass Ultra", "darkglass"]),
    ("Quad Cortex", &["Quad Cortex", "quadcortex"]),
    ("Fortin NTS Suite", &["Fortin NTS Suite", "fortin nts"]),
    ("Soldano SLO-100", &["Soldano SLO-100", "slo-100"]),
    ("BIAS FX 2", &["BIAS FX 2", "bias fx", "biasfx2"]),
    ("BIAS Amp 2", &["BIAS Amp 2", "bias amp", "biasamp2"]),
    ("TH-U", &["TH-U", "overloud th-u"]),
    ("Gem Comp LA", &["Gem Comp LA", "gem comp la"]),
    ("Helix Native", &["Helix Native", "helix native"]),
    ("POD Farm", &["POD Farm", "pod farm"]),
    ("Basslane Pro", &["Basslane Pro", "basslane"]),
    ("Unisum", &["Unisum"]),
    ("Kaleidoscopes", &["Kaleidoscopes"]),
    ("Pro-Q 3", &["Pro-Q 3", "pro-q3", "pro q 3"]),
    ("Pro-Q 4", &["Pro-Q 4", "pro-q4", "pro q 4"]),
    ("Pro-Q 2", &["Pro-Q 2", "pro-q2", "pro q 2"]),
    ("Pro-Q", &["Pro-Q", "pro q"]),
    ("Pro-C 2", &["Pro-C 2", "pro c 2", "pro-c2"]),
    ("Pro-C", &["Pro-C", "pro c"]),
    ("Pro-L 2", &["Pro-L 2", "pro-l2", "pro l 2"]),
    ("Pro-L", &["Pro-L", "pro l"]),
    ("Pro-R", &["Pro-R", "pro r"]),
    ("Pro-R 2", &["Pro-R 2", "pro r 2"]),
    ("Pro-MB", &["Pro-MB", "pro mb", "pro-mb"]),
    ("Pro-DS", &["Pro-DS", "pro ds"]),
    ("Pro-G", &["Pro-G", "pro g"]),
    ("Saturn 2", &["Saturn 2", "saturn2"]),
    ("Saturn", &["Saturn", "fabfilter saturn"]),
    ("Timeless 3", &["Timeless 3", "timeless3"]),
    ("Volcano 3", &["Volcano 3", "volcano3"]),
    ("Twin 3", &["Twin 3", "fabfilter twin"]),
    ("Micro", &["Micro", "fabfilter micro"]),
    ("Simplon", &["Simplon", "fabfilter simplon"]),
    ("One", &["One", "fabfilter one"]),
    ("ValhallaVintageVerb", &["ValhallaVintageVerb", "valhalla vintageverb", "valhalla vintage verb"]),
    ("ValhallaRoom", &["ValhallaRoom", "valhalla room"]),
    ("ValhallaPlate", &["ValhallaPlate", "valhalla plate"]),
    ("ValhallaDelay", &["ValhallaDelay", "valhalla delay"]),
    ("ValhallaShimmer", &["ValhallaShimmer", "valhalla shimmer"]),
    ("ValhallaSupermassive", &["ValhallaSupermassive", "valhalla supermassive"]),
    ("ValhallaUberMod", &["ValhallaUberMod", "valhalla ubermod"]),
    ("ValhallaFreqEcho", &["ValhallaFreqEcho", "freqecho"]),
    ("ValhallaSpaceModulator", &["ValhallaSpaceModulator", "spacemodulator"]),
    ("Decapitator", &["Decapitator", "soundtoys decapitator"]),
    ("EchoBoy", &["EchoBoy", "echo boy", "soundtoys echoboy"]),
    ("Crystallizer", &["Crystallizer"]),
    ("Devil-Loc", &["Devil-Loc", "devil loc", "devil-loc deluxe"]),
    ("PrimalTap", &["PrimalTap", "primal tap"]),
    ("Little Plate", &["Little Plate"]),
    ("Little AlterBoy", &["Little AlterBoy", "alterboy"]),
    ("Little Radiator", &["Little Radiator"]),
    ("Little MicroShift", &["Little MicroShift", "microshift"]),
    ("Tremolator", &["Tremolator"]),
    ("PhaseMistress", &["PhaseMistress", "phase mistress"]),
    ("PanMan", &["PanMan", "pan man"]),
    ("FilterFreak", &["FilterFreak", "filter freak"]),
    ("Sie-Q", &["Sie-Q", "sieq"]),
    ("SuperPlate", &["SuperPlate", "super plate"]),
    ("Effect Rack", &["Effect Rack", "soundtoys rack"]),
    ("Ozone 11", &["Ozone 11", "ozone11"]),
    ("Ozone 10", &["Ozone 10", "ozone10"]),
    ("Ozone 9", &["Ozone 9", "ozone9"]),
    ("Ozone", &["Ozone", "izotope ozone"]),
    ("Neutron 4", &["Neutron 4", "neutron4"]),
    ("Neutron", &["Neutron", "izotope neutron"]),
    ("Nectar 4", &["Nectar 4", "nectar4"]),
    ("Nectar", &["Nectar", "izotope nectar"]),
    ("RX 11", &["RX 11", "rx 11"]),
    ("RX 10", &["RX 10", "rx 10"]),
    ("Trash 2", &["Trash 2", "izotope trash"]),
    ("Vinyl", &["Vinyl", "izotope vinyl"]),
    ("VocalSynth 2", &["VocalSynth 2", "vocalsynth"]),
    ("Stutter Edit 2", &["Stutter Edit 2", "stutter edit"]),
    ("Iris 2", &["Iris 2", "iris2", "izotope iris"]),
    ("Tonal Balance Control 2", &["Tonal Balance Control 2", "tonal balance control"]),
    ("SSL E-Channel", &["SSL E-Channel", "ssl e channel"]),
    ("SSL G-Channel", &["SSL G-Channel", "ssl g channel"]),
    ("SSL G-Master Buss Compressor", &["SSL G-Master Buss Compressor", "ssl g-master", "ssl buss comp"]),
    ("CLA-76", &["CLA-76", "cla 76", "cla-76 compressor"]),
    ("CLA-2A", &["CLA-2A", "cla 2a"]),
    ("CLA-3A", &["CLA-3A", "cla 3a"]),
    ("CLA Vocals", &["CLA Vocals", "cla vocals"]),
    ("CLA Drums", &["CLA Drums", "cla drums"]),
    ("H-Delay", &["H-Delay", "h delay", "h-delay hybrid"]),
    ("H-Comp", &["H-Comp", "h comp"]),
    ("H-EQ", &["H-EQ", "h eq"]),
    ("H-Reverb", &["H-Reverb", "h reverb"]),
    ("Renaissance Vox", &["Renaissance Vox", "rvox", "r-vox"]),
    ("Renaissance Compressor", &["Renaissance Compressor", "rcomp", "r-comp", "renaissance comp"]),
    ("Renaissance Bass", &["Renaissance Bass", "rbass", "r-bass"]),
    ("Renaissance Axx", &["Renaissance Axx", "raxx", "r-axx"]),
    ("L1 Ultramaximizer", &["L1 Ultramaximizer", "l1"]),
    ("L2 Ultramaximizer", &["L2 Ultramaximizer", "l2"]),
    ("L3-16 Multimaximizer", &["L3-16 Multimaximizer", "l3-16"]),
    ("L3-LL Multimaximizer", &["L3-LL Multimaximizer", "l3-ll"]),
    ("Q10 Paragraphic EQ", &["Q10 Paragraphic EQ", "q10"]),
    ("V-EQ3", &["V-EQ3", "v eq3"]),
    ("V-EQ4", &["V-EQ4", "v eq4"]),
    ("API 550A", &["API 550A", "api550a"]),
    ("API 2500", &["API 2500", "api2500"]),
    ("API 560", &["API 560", "api560"]),
    ("Scheps Omni Channel", &["Scheps Omni Channel", "scheps omni"]),
    ("Scheps 73", &["Scheps 73"]),
    ("StudioRack", &["StudioRack", "waves studiorack"]),
    ("Vitamin Sonic Enhancer", &["Vitamin Sonic Enhancer", "vitamin"]),
    ("OneKnob Phatter", &["OneKnob Phatter"]),
    ("OneKnob Louder", &["OneKnob Louder"]),
    ("Kramer Master Tape", &["Kramer Master Tape", "kramer tape"]),
    ("Abbey Road J37", &["Abbey Road J37", "j37"]),
    ("Abbey Road Chambers", &["Abbey Road Chambers"]),
    ("Abbey Road Plates", &["Abbey Road Plates"]),
    ("Abbey Road Vinyl", &["Abbey Road Vinyl"]),
    ("PuigChild", &["PuigChild", "puig child"]),
    ("PuigTec EQs", &["PuigTec EQs", "puigtec"]),
    ("NLS Channel", &["NLS Channel", "nls channel"]),
    ("NLS Buss", &["NLS Buss", "nls buss"]),
    ("NLS Non-Linear Summer", &["NLS Non-Linear Summer", "nls"]),
    ("C4 Multiband Compressor", &["C4 Multiband Compressor", "c4"]),
    ("C6 Multiband Compressor", &["C6 Multiband Compressor", "c6"]),
    ("F6 Floating-Band Dynamic EQ", &["F6 Floating-Band Dynamic EQ", "f6"]),
    ("Smack Attack", &["Smack Attack", "waves smack attack"]),
    ("TrueVerb", &["TrueVerb", "true verb"]),
    ("IR-1", &["IR-1", "ir1", "ir-1 parametric"]),
    ("IR-L", &["IR-L", "irl", "ir-l convolution"]),
    ("IR-Live", &["IR-Live", "ir live"]),
    ("MaxxBass", &["MaxxBass", "waves maxxbass"]),
    ("MaxxVolume", &["MaxxVolume", "maxx volume"]),
    ("OneKnob Filter", &["OneKnob Filter", "1knob filter"]),
    ("OneKnob Pumper", &["OneKnob Pumper", "1knob pumper"]),
    ("OneKnob Brighter", &["OneKnob Brighter", "1knob brighter"]),
    ("OneKnob Driver", &["OneKnob Driver", "1knob driver"]),
    ("OneKnob Wetter", &["OneKnob Wetter", "1knob wetter"]),
    ("Tune Real-Time", &["Tune Real-Time", "waves tune realtime"]),
    ("Tune", &["Tune", "waves tune"]),
    ("GTR3", &["GTR3", "waves gtr3", "gtr 3", "gtr stomp"]),
    ("Doubler", &["Doubler", "waves doubler"]),
    ("Enigma", &["Enigma", "waves enigma"]),
    ("MetaFlanger", &["MetaFlanger", "meta flanger"]),
    ("MondoMod", &["MondoMod", "mondo mod"]),
    ("SuperTap", &["SuperTap", "super tap"]),
    ("S1 Imager", &["S1 Imager", "s1"]),
    ("PS22", &["PS22", "ps22 stereo maker"]),
    ("Center", &["Center", "waves center"]),
    ("Vitamin", &["Vitamin", "waves vitamin"]),
    ("NX", &["NX", "waves nx virtual mix"]),
    ("NX Ocean Way", &["NX Ocean Way", "ocean way nashville"]),
    ("Abbey Road RS127", &["Abbey Road RS127", "rs127"]),
    ("Abbey Road RS56", &["Abbey Road RS56", "rs56"]),
    ("Abbey Road TG Mastering Chain", &["Abbey Road TG Mastering Chain", "tg mastering", "abbey road tg"]),
    ("Abbey Road Studio 3", &["Abbey Road Studio 3", "studio 3", "abbey road studio3"]),
    ("Abbey Road Saturator", &["Abbey Road Saturator", "ar saturator"]),
    ("Abbey Road Reverb Plates", &["Abbey Road Reverb Plates", "reverb plates"]),
    ("Kramer PIE", &["Kramer PIE", "kramer pie"]),
    ("Kramer HLS Channel", &["Kramer HLS Channel", "hls channel"]),
    ("CLA-3A Compressor / Limiter", &["CLA-3A Compressor / Limiter", "cla3a"]),
    ("CLA-76 Compressor / Limiter", &["CLA-76 Compressor / Limiter", "cla76"]),
    ("CLA-2A Compressor / Limiter", &["CLA-2A Compressor / Limiter", "cla2a"]),
    ("CLA Bass", &["CLA Bass", "cla bass"]),
    ("CLA Effects", &["CLA Effects", "cla effects"]),
    ("CLA Guitars", &["CLA Guitars", "cla guitars"]),
    ("CLA MixHub", &["CLA MixHub", "cla mixhub", "mixhub"]),
    ("CLA Unplugged", &["CLA Unplugged", "cla unplugged"]),
    ("CLA Nx", &["CLA Nx", "cla nx"]),
    ("SSL E-Channel Strip", &["SSL E-Channel Strip", "ssl 4000 e"]),
    ("SSL G-Equalizer", &["SSL G-Equalizer", "ssl g eq", "ssl g equalizer"]),
    ("SSL G-Master Compressor", &["SSL G-Master Compressor", "ssl g master", "g master buss"]),
    ("API 550B", &["API 550B", "api 550 b"]),
    ("Q-Clone", &["Q-Clone", "qclone"]),
    ("Q-Series Q1", &["Q-Series Q1", "q1 paragraphic"]),
    ("Q-Series Q2", &["Q-Series Q2", "q2"]),
    ("Q-Series Q3", &["Q-Series Q3", "q3"]),
    ("Q-Series Q4", &["Q-Series Q4", "q4"]),
    ("Q-Series Q6", &["Q-Series Q6", "q6"]),
    ("H-Series H-Comp Hybrid", &["H-Series H-Comp Hybrid", "h comp hybrid"]),
    ("H-Series H-Delay Hybrid", &["H-Series H-Delay Hybrid", "h delay hybrid"]),
    ("H-Reverb", &["H-Reverb", "h-reverb hybrid"]),
    ("Scheps Parallel Particles", &["Scheps Parallel Particles", "parallel particles"]),
    ("Scheps Schillertone", &["Scheps Schillertone", "schillertone"]),
    ("Greg Wells ToneCentric", &["Greg Wells ToneCentric", "tone centric"]),
    ("Greg Wells VoiceCentric", &["Greg Wells VoiceCentric", "voice centric"]),
    ("Greg Wells PianoCentric", &["Greg Wells PianoCentric", "piano centric"]),
    ("Greg Wells MixCentric", &["Greg Wells MixCentric", "mix centric"]),
    ("Eddie Kramer Drums", &["Eddie Kramer Drums", "eddie kramer drums"]),
    ("Eddie Kramer Guitar", &["Eddie Kramer Guitar", "eddie kramer guitar"]),
    ("Eddie Kramer Vocal", &["Eddie Kramer Vocal", "eddie kramer vocal"]),
    ("Eddie Kramer Effects", &["Eddie Kramer Effects", "eddie kramer effects"]),
    ("Tony Maserati Vocal", &["Tony Maserati Vocal", "tony maserati vocal"]),
    ("Tony Maserati Drums", &["Tony Maserati Drums", "tony maserati drums"]),
    ("Tony Maserati Guitar", &["Tony Maserati Guitar", "tony maserati guitar"]),
    ("Jack Joseph Puig Vocals", &["Jack Joseph Puig Vocals", "jjp vocals"]),
    ("Jack Joseph Puig Drums", &["Jack Joseph Puig Drums", "jjp drums"]),
    ("Butch Vig Vocals", &["Butch Vig Vocals", "butch vig vocals"]),
    ("Soothe 2", &["Soothe 2", "soothe2"]),
    ("Spiff", &["Spiff", "oeksound spiff"]),
    ("TDR Nova", &["TDR Nova", "nova ge", "tdr nova"]),
    ("TDR Kotelnikov", &["TDR Kotelnikov", "kotelnikov"]),
    ("TDR SlickEQ", &["TDR SlickEQ", "slickeq", "vos slickeq"]),
    ("TDR Proximity", &["TDR Proximity", "proximity"]),
    ("TDR Limiter 6 GE", &["TDR Limiter 6 GE", "limiter 6"]),
    ("TDR VOS SlickEQ M", &["TDR VOS SlickEQ M", "slickeq m"]),
    ("Span", &["Span", "voxengo span"]),
    ("Elephant", &["Elephant", "voxengo elephant"]),
    ("GlissEQ", &["GlissEQ", "gliss eq"]),
    ("CurveEQ", &["CurveEQ", "curve eq"]),
    ("MSED", &["MSED", "voxengo msed"]),
    ("Vulf Compressor", &["Vulf Compressor", "vulfcompressor"]),
    ("Lossy", &["Lossy", "goodhertz lossy"]),
    ("Faraday Limiter", &["Faraday Limiter", "faraday"]),
    ("Tiltshift", &["Tiltshift", "tilt shift"]),
    ("Tone Control", &["Tone Control", "goodhertz tone control"]),
    ("Canopener Studio", &["Canopener Studio", "canopener"]),
    ("Megaverb", &["Megaverb", "mega verb"]),
    ("Wow Control", &["Wow Control", "wow-control"]),
    ("Good Dither", &["Good Dither", "gooddither"]),
    ("VMR", &["VMR", "virtual mix rack", "vmr 2", "virtualmixrack"]),
    ("VerbSuite Classics", &["VerbSuite Classics", "verbsuite", "verb suite classics"]),
    ("Virtual Buss Compressors", &["Virtual Buss Compressors", "vbc"]),
    ("Virtual Tape Machines", &["Virtual Tape Machines", "vtm"]),
    ("FG-X", &["FG-X", "fgx"]),
    ("FG-X 2", &["FG-X 2", "fgx2", "fg-x2"]),
    ("FG-Bomber", &["FG-Bomber", "fg bomber"]),
    ("FG-N", &["FG-N", "fg-n channel", "fgn"]),
    ("FG-S", &["FG-S", "fg-s channel"]),
    ("FG-MU", &["FG-MU", "fg mu"]),
    ("FG-401", &["FG-401", "fg401"]),
    ("FG-116 Blue", &["FG-116 Blue", "fg-116 blu", "fg116 blue"]),
    ("FG-116 Black", &["FG-116 Black", "fg-116 blk", "fg116 black"]),
    ("FG-Grey", &["FG-Grey", "fg grey"]),
    ("FG-Stress", &["FG-Stress", "fg stress"]),
    ("FG-Bus", &["FG-Bus", "fg bus"]),
    ("Fresh Air", &["Fresh Air", "slate fresh air"]),
    ("Fresh Air Mastering", &["Fresh Air Mastering", "fresh air mastering"]),
    ("Infinity EQ", &["Infinity EQ", "infinity eq"]),
    ("Infinity Bundle", &["Infinity Bundle", "infinity series"]),
    ("Lustrous Plates", &["Lustrous Plates", "lustrous", "lustrous plates reverb"]),
    ("ML-1", &["ML-1", "ml-1 microphone"]),
    ("ML-2", &["ML-2", "ml-2 microphone"]),
    ("VSX", &["VSX", "vsx headphone"]),
    ("Trigger 2", &["Trigger 2", "slate trigger", "trigger2"]),
    ("Steven Slate Drums 5", &["Steven Slate Drums 5", "steven slate drums", "ssd 5"]),
    ("Virtual Drummer", &["Virtual Drummer", "slate virtual drummer"]),
    ("Eiosis AirEQ", &["Eiosis AirEQ", "aireq", "eiosis air eq"]),
    ("Eiosis E2 De-Esser", &["Eiosis E2 De-Esser", "eiosis deesser", "e2 deesser"]),
    ("Eiosis EReverb", &["Eiosis EReverb", "ereverb"]),
    ("Repeater", &["Repeater", "slate repeater"]),
    ("Monster BVC", &["Monster BVC", "monster bvc"]),
    ("Raven", &["Raven", "slate raven"]),
    ("bx_console SSL 4000 E", &["bx_console SSL 4000 E", "bx console ssl 4000 e", "bx_console 4000 e"]),
    ("bx_console SSL 9000 J", &["bx_console SSL 9000 J", "bx console ssl 9000 j"]),
    ("bx_console N", &["bx_console N", "bx console n"]),
    ("bx_console AMEK 9099", &["bx_console AMEK 9099", "amek 9099"]),
    ("bx_digital V3", &["bx_digital V3", "bx digital v3", "bx_digital v3"]),
    ("bx_masterdesk", &["bx_masterdesk", "bx masterdesk"]),
    ("bx_limiter True Peak", &["bx_limiter True Peak", "bx limiter"]),
    ("bx_saturator V2", &["bx_saturator V2", "bx saturator"]),
    ("bx_subsynth", &["bx_subsynth", "bx subsynth"]),
    ("Maag EQ4", &["Maag EQ4", "maag eq 4"]),
    ("Shadow Hills Mastering Compressor", &["Shadow Hills Mastering Compressor", "shadow hills"]),
    ("Lindell 80 Series", &["Lindell 80 Series", "lindell 80"]),
    ("Lindell 902 De-Esser", &["Lindell 902 De-Esser", "lindell 902"]),
    ("Lindell 6X-500", &["Lindell 6X-500", "lindell 6x"]),
    ("Lindell 7X-500", &["Lindell 7X-500", "lindell 7x"]),
    ("Lindell 254E", &["Lindell 254E", "lindell 254"]),
    ("Lindell 354E", &["Lindell 354E", "lindell 354"]),
    ("Vertigo VSC-2", &["Vertigo VSC-2", "vsc-2"]),
    ("Elysia Alpha Master", &["Elysia Alpha Master", "elysia alpha"]),
    ("Elysia Museq", &["Elysia Museq", "museq"]),
    ("Elysia Mpressor", &["Elysia Mpressor", "mpressor"]),
    ("Elysia Karacter", &["Elysia Karacter", "karacter"]),
    ("Elysia Nvelope", &["Elysia Nvelope", "nvelope"]),
    ("ADA STM-1 Stereo Tapped Delay", &["ADA STM-1 Stereo Tapped Delay", "stm-1"]),
    ("UAD LA-2A", &["UAD LA-2A", "la2a", "la-2a", "teletronix la-2a"]),
    ("UAD 1176", &["UAD 1176", "1176ln", "uad 1176", "1176 rev a", "1176ae", "urei 1176"]),
    ("UAD Fairchild 670", &["UAD Fairchild 670", "fairchild 670", "fairchild 660", "fairchild"]),
    ("UAD Pultec EQP-1A", &["UAD Pultec EQP-1A", "pultec eqp-1a", "pultec pro", "pultec passive"]),
    ("UAD Pultec MEQ-5", &["UAD Pultec MEQ-5", "meq-5"]),
    ("UAD Pultec HLF-3C", &["UAD Pultec HLF-3C", "hlf-3c"]),
    ("UAD API 2500", &["UAD API 2500", "uad api 2500"]),
    ("UAD API 550A", &["UAD API 550A", "uad api 550a"]),
    ("UAD API 550B", &["UAD API 550B", "uad api 550b"]),
    ("UAD API 560", &["UAD API 560", "uad api 560"]),
    ("UAD API Vision Channel Strip", &["UAD API Vision Channel Strip", "api vision"]),
    ("UAD API Preamp", &["UAD API Preamp", "api preamp"]),
    ("UAD Neve 1073", &["UAD Neve 1073", "neve 1073", "1073 preamp"]),
    ("UAD Neve 1084", &["UAD Neve 1084", "neve 1084"]),
    ("UAD Neve 88RS", &["UAD Neve 88RS", "neve 88rs", "88rs channel"]),
    ("UAD Neve 31102", &["UAD Neve 31102", "neve 31102"]),
    ("UAD Neve 33609", &["UAD Neve 33609", "neve 33609"]),
    ("UAD SSL 4000 E", &["UAD SSL 4000 E", "ssl e-series", "uad ssl 4000", "ssl 4000 e"]),
    ("UAD SSL 4000 G", &["UAD SSL 4000 G", "ssl 4000 g", "ssl g series"]),
    ("UAD SSL G Bus Compressor", &["UAD SSL G Bus Compressor", "ssl g comp", "uad ssl g"]),
    ("UAD SSL E Channel Strip", &["UAD SSL E Channel Strip", "ssl e channel"]),
    ("UAD Helios Type 69", &["UAD Helios Type 69", "helios 69", "type 69"]),
    ("UAD Studer A800", &["UAD Studer A800", "studer a800", "studer tape"]),
    ("UAD Ampex ATR-102", &["UAD Ampex ATR-102", "atr-102", "ampex atr"]),
    ("UAD LA-610", &["UAD LA-610", "la-610"]),
    ("UAD LA-3A", &["UAD LA-3A", "la3a", "la-3a audio"]),
    ("UAD 1176AE", &["UAD 1176AE", "1176 ae"]),
    ("UAD Manley Massive Passive", &["UAD Manley Massive Passive", "massive passive", "manley massive"]),
    ("UAD Manley Variable Mu", &["UAD Manley Variable Mu", "manley vari-mu", "variable-mu"]),
    ("UAD Manley VOXBOX", &["UAD Manley VOXBOX", "voxbox", "manley voxbox"]),
    ("UAD Capitol Chambers", &["UAD Capitol Chambers", "capitol chambers"]),
    ("UAD Ocean Way Studios", &["UAD Ocean Way Studios", "ocean way studios"]),
    ("UAD Lexicon 224", &["UAD Lexicon 224", "lexicon 224"]),
    ("UAD Lexicon 480L", &["UAD Lexicon 480L", "lexicon 480", "480l"]),
    ("UAD EMT 140", &["UAD EMT 140", "emt 140"]),
    ("UAD EMT 250", &["UAD EMT 250", "emt 250"]),
    ("UAD Pure Plate", &["UAD Pure Plate", "pure plate"]),
    ("UAD AKG BX 20", &["UAD AKG BX 20", "bx 20", "bx20"]),
    ("UAD Oxford Inflator", &["UAD Oxford Inflator", "oxford inflator"]),
    ("UAD Precision K-Stereo", &["UAD Precision K-Stereo", "k-stereo"]),
    ("UAD Precision Limiter", &["UAD Precision Limiter", "precision limiter"]),
    ("UAD Precision Maximizer", &["UAD Precision Maximizer", "precision maximizer"]),
    ("UAD Precision Multiband", &["UAD Precision Multiband", "precision multiband"]),
    ("UAD Galaxy Tape Echo", &["UAD Galaxy Tape Echo", "galaxy tape", "roland re-201 uad"]),
    ("UAD Dreamverb", &["UAD Dreamverb", "dreamverb"]),
    ("UAD RealVerb Pro", &["UAD RealVerb Pro", "realverb"]),
    ("UAD Cooper Time Cube", &["UAD Cooper Time Cube", "cooper time cube"]),
    ("UAD Cambridge EQ", &["UAD Cambridge EQ", "cambridge eq"]),
    ("UAD Fatso Jr/Sr", &["UAD Fatso Jr/Sr", "fatso"]),
    ("UAD Chandler Limited TG1", &["UAD Chandler Limited TG1", "chandler tg1"]),
    ("UAD Chandler Limited Curve Bender", &["UAD Chandler Limited Curve Bender", "curve bender"]),
    ("UAD Chandler Limited Zener Limiter", &["UAD Chandler Limited Zener Limiter", "zener limiter"]),
    ("UAD Empirical Labs FATSO", &["UAD Empirical Labs FATSO", "empirical labs fatso"]),
    ("UAD Empirical Labs Distressor", &["UAD Empirical Labs Distressor", "distressor"]),
    ("UAD Moog Multimode Filter", &["UAD Moog Multimode Filter", "moog multimode"]),
    ("UAD Teletronix LA-2A", &["UAD Teletronix LA-2A", "teletronix la-2a silver"]),
    ("UAD Thermionic Culture Vulture", &["UAD Thermionic Culture Vulture", "culture vulture"]),
    ("UAD Avalon VT-737sp", &["UAD Avalon VT-737sp", "avalon vt-737", "vt-737sp"]),
    ("UAD dbx 160", &["UAD dbx 160", "dbx 160"]),
    ("UAD Moog Minimoog", &["UAD Moog Minimoog", "uad minimoog"]),
    ("UAD Waterfall B3", &["UAD Waterfall B3", "waterfall b3", "uad b3"]),
    ("UAD Opal Synth", &["UAD Opal Synth", "uad opal"]),
    ("Console 1", &["Console 1", "softube console 1"]),
    ("Tape", &["Tape", "softube tape"]),
    ("Saturation Knob", &["Saturation Knob", "sat knob", "saturation-knob"]),
    ("Vintage Amp Room", &["Vintage Amp Room", "softube vintage amp"]),
    ("Metal Amp Room", &["Metal Amp Room", "metal amp"]),
    ("Bass Amp Room", &["Bass Amp Room", "softube bass amp"]),
    ("Drawmer S73", &["Drawmer S73", "drawmer s73"]),
    ("Drawmer 1973", &["Drawmer 1973", "drawmer 1973"]),
    ("Tube-Tech CL 1B", &["Tube-Tech CL 1B", "cl 1b", "tube-tech cl1b", "tube tech cl-1b"]),
    ("Tube-Tech PE 1C", &["Tube-Tech PE 1C", "pe 1c", "tube-tech pe"]),
    ("Tube-Tech ME 1B", &["Tube-Tech ME 1B", "me 1b"]),
    ("Abbey Road TG12413", &["Abbey Road TG12413", "tg12413"]),
    ("Trident A-Range", &["Trident A-Range", "trident a range", "a-range"]),
    ("Weiss DS1-MK3", &["Weiss DS1-MK3", "weiss ds1"]),
    ("Weiss EQ MP", &["Weiss EQ MP", "weiss eq"]),
    ("Weiss Gambit", &["Weiss Gambit", "weiss gambit"]),
    ("Chandler Limited Germanium", &["Chandler Limited Germanium", "chandler germanium"]),
    ("Valley People Dyna-Mite", &["Valley People Dyna-Mite", "dyna-mite", "valley people"]),
    ("Spring Reverb", &["Spring Reverb", "softube spring reverb"]),
    ("Model 72 Synthesizer System", &["Model 72 Synthesizer System", "model 72", "softube model 72"]),
    ("Model 84 Polyphonic Synthesizer", &["Model 84 Polyphonic Synthesizer", "model 84"]),
    ("Volume II", &["Volume II", "softube volume"]),
    ("Harmonics Analog Saturation Processor", &["Harmonics Analog Saturation Processor", "softube harmonics"]),
    ("Parallels", &["Parallels", "softube parallels"]),
    ("Eden WT800", &["Eden WT800", "eden wt800"]),
    ("Transient Shaper", &["Transient Shaper", "softube transient shaper"]),
    ("Transient Designer", &["Transient Designer", "spl transient designer", "transient designer plus"]),
    ("Attacker", &["Attacker", "spl attacker"]),
    ("Vitalizer MK2-T", &["Vitalizer MK2-T", "vitalizer", "spl vitalizer"]),
    ("IRON", &["IRON", "spl iron"]),
    ("PassEQ", &["PassEQ", "spl passeq", "pass eq"]),
    ("FullRanger", &["FullRanger", "full ranger", "full-ranger"]),
    ("MicroDynamics", &["MicroDynamics", "micro dynamics"]),
    ("De-Esser", &["De-Esser", "spl de-esser"]),
    ("Mo-Verb", &["Mo-Verb", "moverb", "spl mo-verb"]),
    ("Equilibrium", &["Equilibrium", "dmg equilibrium"]),
    ("Limitless", &["Limitless", "dmg limitless"]),
    ("TrackComp", &["TrackComp", "track comp", "dmg trackcomp"]),
    ("TrackDS", &["TrackDS", "track ds"]),
    ("TrackLimit", &["TrackLimit", "track limit"]),
    ("EQuality", &["EQuality", "dmg equality"]),
    ("EQuick", &["EQuick", "dmg equick"]),
    ("Compassion", &["Compassion", "dmg compassion"]),
    ("Dualism", &["Dualism", "dmg dualism"]),
    ("Essence", &["Essence", "dmg essence"]),
    ("Multiplicity", &["Multiplicity", "dmg multiplicity"]),
    ("The Glue", &["The Glue", "cytomic glue"]),
    ("The Drop", &["The Drop", "cytomic drop"]),
    ("The Plug", &["The Plug", "cytomic plug"]),
    ("Falcon", &["Falcon", "uvi falcon"]),
    ("Workstation", &["Workstation", "uvi workstation"]),
    ("Digital Synsations", &["Digital Synsations", "synsations", "digital synsations vintage"]),
    ("Vector Pro", &["Vector Pro", "uvi vector"]),
    ("Mission 2", &["Mission 2", "uvi mission"]),
    ("Quadra", &["Quadra", "uvi quadra"]),
    ("BeatBox Anthology", &["BeatBox Anthology", "beatbox anthology"]),
    ("Drum Designer", &["Drum Designer", "uvi drum designer"]),
    ("Emulation II+", &["Emulation II+", "emulation ii"]),
    ("Emulation One", &["Emulation One", "emulation one"]),
    ("Vintage Legends", &["Vintage Legends", "vintage legends"]),
    ("Orchestral Suite", &["Orchestral Suite", "orchestral suite"]),
    ("Synth Anthology", &["Synth Anthology", "synth anthology"]),
    ("Hybrid", &["Hybrid", "uvi hybrid"]),
    ("Retro Organ Suite", &["Retro Organ Suite", "retro organ suite"]),
    ("smart:EQ 3", &["smart:EQ 3", "smart eq", "sonible smart:eq"]),
    ("smart:comp 2", &["smart:comp 2", "smart comp", "sonible smart:comp"]),
    ("smart:limit", &["smart:limit", "smart limit", "sonible smart:limit"]),
    ("smart:reverb", &["smart:reverb", "smart reverb"]),
    ("smart:deess", &["smart:deess", "smart deess"]),
    ("smart:gate", &["smart:gate", "smart gate"]),
    ("entropy:EQ+", &["entropy:EQ+", "entropy eq"]),
    ("pure:unmask", &["pure:unmask", "pure unmask"]),
    ("true:balance", &["true:balance", "true balance"]),
    ("LuSH-101", &["LuSH-101", "lush 101", "lush-101"]),
    ("Drumazon", &["Drumazon"]),
    ("Nepheton", &["Nepheton"]),
    ("Phoscyon", &["Phoscyon", "phoscyon 2"]),
    ("Nithonat", &["Nithonat"]),
    ("Repeater", &["Repeater", "d16 repeater"]),
    ("Devastor 2", &["Devastor 2", "devastor"]),
    ("Decimort 2", &["Decimort 2", "decimort"]),
    ("Frontier", &["Frontier", "d16 frontier"]),
    ("Syntorus 2", &["Syntorus 2", "syntorus"]),
    ("Fazortan 2", &["Fazortan 2", "fazortan"]),
    ("Antresol", &["Antresol", "d16 antresol"]),
    ("Redoptor 2", &["Redoptor 2", "redoptor"]),
    ("Sigmund", &["Sigmund", "d16 sigmund"]),
    ("Toraverb 2", &["Toraverb 2", "toraverb"]),
    ("Tekturon", &["Tekturon", "d16 tekturon"]),
    ("Intensity", &["Intensity", "zynaptiq intensity"]),
    ("Unveil", &["Unveil", "zynaptiq unveil"]),
    ("Morph 2", &["Morph 2", "zynaptiq morph"]),
    ("Orange Vocoder IV", &["Orange Vocoder IV", "orange vocoder"]),
    ("Adaptiverb", &["Adaptiverb", "adaptive verb"]),
    ("Wormhole", &["Wormhole", "zynaptiq wormhole"]),
    ("Subgenix", &["Subgenix", "sub genix"]),
    ("Unmix::Drums", &["Unmix::Drums", "unmix drums"]),
    ("Unfilter", &["Unfilter", "zynaptiq unfilter"]),
    ("Pitchmap", &["Pitchmap", "pitch map"]),
    ("Axon 2", &["Axon 2", "audio damage axon"]),
    ("Phosphor 3", &["Phosphor 3", "phosphor"]),
    ("Replicant 3", &["Replicant 3", "replicant"]),
    ("Rough Rider 3", &["Rough Rider 3", "rough rider", "roughrider"]),
    ("Dubstation 2", &["Dubstation 2", "dubstation"]),
    ("Eos 2", &["Eos 2", "audio damage eos"]),
    ("Filterstation 2", &["Filterstation 2", "filterstation"]),
    ("Continua", &["Continua"]),
    ("Panstation 2", &["Panstation 2", "panstation"]),
    ("Quanta 2", &["Quanta 2", "audio damage quanta"]),
    ("VLA-2A", &["VLA-2A", "vla 2a", "black rooster vla-2a"]),
    ("VLA-3A", &["VLA-3A", "vla 3a"]),
    ("VLA-FET", &["VLA-FET", "vla fet"]),
    ("VHL-3C", &["VHL-3C"]),
    ("PE-20", &["PE-20", "pe 20"]),
    ("BRM-12P", &["BRM-12P", "brm 12p"]),
    ("Omnia", &["Omnia", "black rooster omnia"]),
    ("VPRE-376", &["VPRE-376", "vpre 376"]),
    ("VPRE-73", &["VPRE-73", "vpre 73"]),
    ("Cypress TT-15", &["Cypress TT-15", "cypress", "cypress tt15"]),
    ("Opal", &["Opal", "tone empire opal"]),
    ("Loc-Ness", &["Loc-Ness", "locness"]),
    ("Alexandrite", &["Alexandrite", "tone empire alexandrite"]),
    ("Black Q", &["Black Q", "blackq"]),
    ("Model N", &["Model N", "tone empire model n"]),
    ("Goliath", &["Goliath", "tone empire goliath"]),
    ("R0Verb", &["R0Verb", "r0 verb", "roverb"]),
    ("Esspresso", &["Esspresso", "klevgrand esspresso"]),
    ("Svep", &["Svep", "klevgrand svep"]),
    ("Pana", &["Pana", "klevgrand pana"]),
    ("REAMP", &["REAMP", "klevgrand reamp"]),
    ("Haaze 2", &["Haaze 2", "haaze"]),
    ("Brusfri", &["Brusfri", "klevgrand brusfri"]),
    ("GotoEQ", &["GotoEQ", "goto eq"]),
    ("Acoustica", &["Acoustica", "acon acoustica"]),
    ("Verberate", &["Verberate", "acon verberate"]),
    ("DeVerberate", &["DeVerberate", "de-verberate"]),
    ("Equalize", &["Equalize", "acon equalize"]),
    ("Multiply", &["Multiply", "acon multiply"]),
    ("Remix", &["Remix", "acon remix"]),
    ("Restoration Suite", &["Restoration Suite", "restoration-suite"]),
    ("Biotek 2", &["Biotek 2", "biotek"]),
    ("Waveform", &["Waveform", "waveform free"]),
    ("Abyss", &["Abyss", "tracktion abyss"]),
    ("F.'em", &["F.'em", "f-em", "fem synth"]),
    ("Hyperion", &["Hyperion", "tracktion hyperion"]),
    ("HoRNet VU Meter MK4", &["HoRNet VU Meter MK4", "hornet vu meter"]),
    ("Multi Comp Plus", &["Multi Comp Plus", "multi comp plus"]),
    ("ThirtyOne", &["ThirtyOne", "thirty one"]),
    ("Magnus", &["Magnus", "hornet magnus"]),
    ("Harmoniq", &["Harmoniq", "hornet harmoniq"]),
    ("BUTE Loudness", &["BUTE Loudness", "bute loudness"]),
    ("BUTE Batch", &["BUTE Batch", "bute batch"]),
    ("Bute Loudness Suite", &["Bute Loudness Suite", "loudness suite"]),
    ("R2 Surround Reverb", &["R2 Surround Reverb", "r2"]),
    ("R4 Surround Reverb", &["R4 Surround Reverb", "r4"]),
    ("PhoenixVerb", &["PhoenixVerb", "phoenix verb"]),
    ("Nimbus", &["Nimbus", "expon nimbus"]),
    ("Symphony", &["Symphony", "expon symphony"]),
    ("Excalibur", &["Excalibur", "expon excalibur"]),
    ("Stratus", &["Stratus", "expon stratus"]),
    ("SSL Native Bus Compressor", &["SSL Native Bus Compressor", "ssl native buscomp", "ssl bus compressor native"]),
    ("SSL Native X-Comp", &["SSL Native X-Comp", "x-comp"]),
    ("SSL Native X-EQ", &["SSL Native X-EQ", "x-eq"]),
    ("SSL Native X-ValveComp", &["SSL Native X-ValveComp", "x-valvecomp"]),
    ("SSL Native X-Phase", &["SSL Native X-Phase", "x-phase"]),
    ("SSL Native Channel Strip", &["SSL Native Channel Strip", "ssl native channel"]),
    ("SSL Vocalstrip 2", &["SSL Vocalstrip 2", "vocalstrip"]),
    ("SSL Drumstrip", &["SSL Drumstrip", "drumstrip"]),
    ("SSL Native Essentials", &["SSL Native Essentials", "ssl essentials"]),
    ("Blackhole", &["Blackhole", "eventide blackhole"]),
    ("H910 Harmonizer", &["H910 Harmonizer", "h910"]),
    ("H949 Harmonizer", &["H949 Harmonizer", "h949"]),
    ("H3000 Factory", &["H3000 Factory", "h3000"]),
    ("SP2016 Reverb", &["SP2016 Reverb", "sp2016"]),
    ("Fission", &["Fission", "eventide fission"]),
    ("Physion", &["Physion", "eventide physion"]),
    ("MicroPitch", &["MicroPitch", "micro pitch"]),
    ("Ultrachannel", &["Ultrachannel", "ultra channel"]),
    ("CrushStation", &["CrushStation", "crush station"]),
    ("MangledVerb", &["MangledVerb", "mangled verb"]),
    ("PitchFlex", &["PitchFlex", "pitch flex"]),
    ("SplitEQ", &["SplitEQ", "split eq"]),
    ("Omnipressor", &["Omnipressor"]),
    ("UltraTap", &["UltraTap", "ultra tap"]),
    ("Elevate", &["Elevate", "newfangled elevate"]),
    ("Equivocate", &["Equivocate", "equivocate"]),
    ("Saturate", &["Saturate", "newfangled saturate"]),
    ("Punctuate", &["Punctuate"]),
    ("Invigorate", &["Invigorate"]),
    ("ShaperBox 3", &["ShaperBox 3", "shaperbox3", "shaperbox 2", "shaper box"]),
    ("VolumeShaper 6", &["VolumeShaper 6", "volumeshaper", "volume shaper"]),
    ("TimeShaper 2", &["TimeShaper 2", "timeshaper"]),
    ("FilterShaper Core 2", &["FilterShaper Core 2", "filtershaper"]),
    ("PanShaper 3", &["PanShaper 3", "panshaper"]),
    ("DriveShaper", &["DriveShaper", "drive shaper"]),
    ("CrushShaper", &["CrushShaper", "crush shaper"]),
    ("NoiseShaper", &["NoiseShaper", "noise shaper"]),
    ("ReverbShaper", &["ReverbShaper", "reverb shaper"]),
    ("LiquidPitch", &["LiquidPitch", "liquid pitch"]),
    ("HalftimePro", &["HalftimePro", "halftime pro", "halftime"]),
    ("Parallel Aggressor", &["Parallel Aggressor", "parallel aggressor"]),
    ("Super VHS", &["Super VHS", "supervhs"]),
    ("Crystalline", &["Crystalline", "baby audio crystalline"]),
    ("I Heart NY", &["I Heart NY", "i <3 ny", "heart ny"]),
    ("Magic Switch", &["Magic Switch"]),
    ("Pitch Drift", &["Pitch Drift"]),
    ("Comeback Kid", &["Comeback Kid", "comeback"]),
    ("Smooth Operator", &["Smooth Operator"]),
    ("Spaced Out", &["Spaced Out"]),
    ("TAIP", &["TAIP"]),
    ("Sand", &["Sand", "acustica sand"]),
    ("Amber", &["Amber", "acustica amber"]),
    ("Ash", &["Ash", "acustica ash"]),
    ("Violet", &["Violet", "acustica violet"]),
    ("Taupe", &["Taupe", "acustica taupe"]),
    ("Onyx", &["Onyx", "acustica onyx"]),
    ("Cobalt", &["Cobalt", "acustica cobalt"]),
    ("OTT", &["OTT", "xfer ott"]),
    ("LFO Tool", &["LFO Tool", "lfotool", "lfo-tool"]),
    ("Kickstart 2", &["Kickstart 2", "kickstart2"]),
    ("Kickstart", &["Kickstart", "nicky romero kickstart"]),
    ("CamelCrusher", &["CamelCrusher", "camel crusher"]),
    ("Camel Phat", &["Camel Phat", "camelphat"]),
    ("Endless Smile", &["Endless Smile", "endlessmile"]),
    ("Gullfoss", &["Gullfoss", "soundtheory gullfoss"]),
    ("Ozone Imager 2", &["Ozone Imager 2", "ozone imager"]),
    ("Vocal Rider", &["Vocal Rider", "waves vocal rider"]),
    ("Auto-Tune", &["Auto-Tune", "autotune", "auto tune", "antares autotune"]),
    ("Auto-Tune Pro", &["Auto-Tune Pro", "auto-tune pro"]),
    ("Melodyne", &["Melodyne", "celemony melodyne"]),
    ("ArtsAcoustic Reverb", &["ArtsAcoustic Reverb", "artsacousticreverb", "aa reverb"]),
    ("Ozone Elements", &["Ozone Elements", "ozone elements"]),
    ("Ozone Standard", &["Ozone Standard", "ozone standard"]),
    ("Ozone Advanced", &["Ozone Advanced", "ozone advanced"]),
    ("Neutron Elements", &["Neutron Elements", "neutron elements"]),
    ("Neutron Standard", &["Neutron Standard", "neutron standard"]),
    ("Neutron Advanced", &["Neutron Advanced", "neutron advanced"]),
    ("Nectar Elements", &["Nectar Elements", "nectar elements"]),
    ("Nectar Production Suite", &["Nectar Production Suite", "nectar production"]),
    ("RX Elements", &["RX Elements", "rx elements"]),
    ("RX Standard", &["RX Standard", "rx standard"]),
    ("RX Advanced", &["RX Advanced", "rx advanced"]),
    ("Insight 2", &["Insight 2", "izotope insight"]),
    ("Music Rebalance", &["Music Rebalance", "music rebalance"]),
    ("Relay", &["Relay", "izotope relay"]),
    ("Dialog De-clicker", &["Dialog De-clicker", "de-clicker"]),
    ("De-crackle", &["De-crackle"]),
    ("De-hum", &["De-hum"]),
    ("De-noise", &["De-noise", "voice denoise"]),
    ("Dialogue Match", &["Dialogue Match", "dialogue-match"]),
    ("Breath Control", &["Breath Control", "breath-control"]),
    ("Drift", &["Drift", "ableton drift"]),
    ("Meld", &["Meld", "ableton meld"]),
    ("Operator", &["Operator", "ableton operator"]),
    ("Analog", &["Analog", "ableton analog"]),
    ("Electric", &["Electric", "ableton electric"]),
    ("Tension", &["Tension", "ableton tension"]),
    ("Collision", &["Collision", "ableton collision"]),
    ("Wavetable", &["Wavetable", "ableton wavetable"]),
    ("Roar", &["Roar", "ableton roar"]),
    ("Shifter", &["Shifter", "ableton shifter"]),
    ("Shaper", &["Shaper", "ableton shaper"]),
    ("Hybrid Reverb", &["Hybrid Reverb", "hybrid-reverb"]),
    ("Spectral Resonator", &["Spectral Resonator"]),
    ("Spectral Time", &["Spectral Time"]),
    ("Analog Keys", &["Analog Keys", "output analog keys"]),
    ("Stems", &["Stems", "output stems"]),
    ("Clariphonic", &["Clariphonic", "clariphonic dsp"]),
    ("Pusher", &["Pusher", "kush pusher"]),
    ("Omega", &["Omega", "kush omega"]),
    ("Electra", &["Electra", "kush electra"]),
    ("Oxford Inflator", &["Oxford Inflator", "oxford inflator"]),
    ("Oxford Limiter", &["Oxford Limiter", "oxford limiter"]),
    ("Oxford EQ", &["Oxford EQ", "oxford eq"]),
    ("Oxford Dynamics", &["Oxford Dynamics", "oxford dynamics"]),
    ("Oxford SuprEsser", &["Oxford SuprEsser", "supresser"]),
    ("Reels", &["Reels", "audiothing reels"]),
    ("Wires", &["Wires", "audiothing wires"]),
    ("Things - Delays", &["Things - Delays", "things delays"]),
    ("Things - Pigeon", &["Things - Pigeon", "things pigeon"]),
    ("Manipulator", &["Manipulator", "polyverse manipulator"]),
    ("I Wish", &["I Wish", "iwish", "polyverse iwish"]),
    ("Infected Mushroom Pusher", &["Infected Mushroom Pusher", "im pusher"]),
    ("Gatekeeper", &["Gatekeeper", "polyverse gatekeeper"]),
    ("Hoser XT", &["Hoser XT", "hoser"]),
    ("Big Clipper", &["Big Clipper", "big clipper"]),
    ("The Wall", &["The Wall", "boz the wall"]),
    ("ISOL8", &["ISOL8", "isol8"]),
    ("dpMeter", &["dpMeter", "dpmeter"]),
    ("GainRider", &["GainRider"]),
    ("mvMeter", &["mvMeter"]),
    ("StageOne", &["StageOne", "stage one"]),
    ("DynOne", &["DynOne", "dyn one"]),
    ("CenterOne", &["CenterOne", "center one"]),
    ("Pulsar Massive", &["Pulsar Massive", "pulsar massive"]),
    ("Pulsar Mu", &["Pulsar Mu", "pulsar mu"]),
    ("Pulsar 1178", &["Pulsar 1178", "pulsar 1178"]),
    ("Pulsar W495", &["Pulsar W495", "pulsar w495"]),
    ("Smasher", &["Smasher", "pulsar smasher"]),
    ("IVGI", &["IVGI", "klanghelm ivgi"]),
    ("SDRR", &["SDRR", "klanghelm sdrr"]),
    ("MJUC", &["MJUC", "klanghelm mjuc"]),
    ("DC1A", &["DC1A", "klanghelm dc1a"]),
    ("DC8C", &["DC8C", "klanghelm dc8c"]),
    ("MAutoPitch", &["MAutoPitch", "mautopitch"]),
    ("MCompressor", &["MCompressor"]),
    ("MEqualizer", &["MEqualizer"]),
    ("MAutoDynamicEq", &["MAutoDynamicEq"]),
    ("MConvolutionEZ", &["MConvolutionEZ"]),
];

/// Check which known plugins the user has installed.
pub fn check_compatibility(installed: &[InstalledPlugin]) -> Vec<(String, bool)> {
    let installed_lower: Vec<String> = installed.iter()
        .map(|p| p.name.to_lowercase())
        .collect();

    KNOWN_PLUGINS.iter().map(|(canonical_name, variants)| {
        let found = variants.iter().any(|v| {
            let v_lower = v.to_lowercase();
            installed_lower.iter().any(|installed_name| {
                installed_name.contains(&v_lower) || v_lower.contains(installed_name)
            })
        });
        (canonical_name.to_string(), found)
    }).collect()
}
